// vue2-simple-chat/src/components/composer/MessageComposer.vue
<template>
  <div class="message-composer">
    <attachment v-if="file" :file="file" @delete="resetState" />

    <form ref="form" @submit.prevent="sendMessage">
      <div class="uploaders">
        <uploader accept="image/*" @input="val => file = val">
          <image-icon />
        </uploader>

        <uploader accept="*/*" @input="val => file = val">
          <file-icon />
        </uploader>
      </div>

      <input
        type="text"
        name="text"
        v-model="text"
        placeholder="Type something..."
        autoComplete="off"
        autoCorrect="off"
      />

      <button>
        <send-icon />
      </button>
    </form>
  </div>
</template>

<script>
import { MessageRepository } from "@amityco/js-sdk";

import ImageComponent from "@/components/Image";

import Attachment from "./Attachment";
import Uploader from "./Uploader";

import ImageIcon from "@/components/icons/ImageIcon";
import FileIcon from "@/components/icons/FileIcon";
import SendIcon from "@/components/icons/SendIcon";

export default {
  components: {
    Attachment,
    Uploader,
    ImageComponent,
    ImageIcon,
    FileIcon,
    SendIcon,
  },

  props: ["channelId"],

  data: () => ({
    text: "",
    file: null,
  }),

  methods: {
    resetState() {
      this.text = ''
      this.file = null
      this.$refs.form.reset()
    },

    sendMessage() {
      if (!this.file) {
        MessageRepository.createTextMessage({
          channelId: this.channelId,
          text: this.text,
        });
      } else if (this.file.type === "image") {
        MessageRepository.createImageMessage({
          channelId: this.channelId,
          imageId: this.file.fileId,
          caption: this.text,
        });
      } else if (this.file.type === "file") {
        MessageRepository.createFileMessage({
          channelId: this.channelId,
          fileId: this.file.fileId,
          caption: this.text,
        });
      }

      this.resetState();
    },
  },
};
</script>

<style>
.message-composer {
  display: flex;
  flex-direction: column;
  width: 100%;
  padding: 1rem 0.5rem 1rem 1rem;
  border-top: 1px solid #ccd0d5;
}

.message-composer form {
  display: grid;
  width: 100%;
  grid-template-columns: min-content 1fr min-content;
  grid-template-rows: 100%;
  grid-gap: 0.5rem;
}

.message-composer .uploaders {
  flex: 0 0 auto;
  display: flex;
}

.message-composer form input[type="text"] {
  flex: 1 1 auto;
  display: block;
  width: 100%;
  min-width: 0;
  padding: 0.6rem 1.2rem;
  border: 1px solid #ccd0d5;
  border-radius: 0.25rem;
  font-size: 1rem;
}

.message-composer form button {
  flex: 0 0 auto;
  background: none;
  border: none;
  cursor: pointer;
}
</style>

// messaging-app-with-angular/src/app/chat/MessageComposer/message-composer.component.ts
import { Component, Input, ViewChild } from "@angular/core";
import { Validators, FormBuilder } from "@angular/forms";
import { FileType, FileRepository, MessageRepository } from "@amityco/js-sdk";

@Component({
  selector: "app-message-composer",
  templateUrl: "./message-composer.component.html",
  styleUrls: ["./message-composer.component.css"]
})
export class MessageComposer {
  @ViewChild("fileInput") fileInput;
  @ViewChild("imageInput") imageInput;
  @Input() channelId;
  chatForm;
  file;

  constructor(private formBuilder: FormBuilder) {
    this.chatForm = formBuilder.group({
      message: ["", [Validators.required]]
    });
  }

  async onSubmit() {
    if (this.chatForm.status === "VALID" || this.file) {
      let channelId = this.channelId;
      let text, caption, fileId, imageId;
      text = caption = this.chatForm.get("message").value?.length
        ? this.chatForm.get("message").value
        : undefined;
      imageId = fileId = this.file.model.fileId;

      if (!this.file) {
        MessageRepository.createTextMessage({ channelId, text });
      } else if (this.file.model.type === FileType.Image) {
        MessageRepository.createImageMessage({ channelId, imageId, caption });
      } else if (this.file.model.type === FileType.File) {
        MessageRepository.createFileMessage({ channelId, fileId, caption });
      }
      this.chatForm.reset();
      this.resetFiles();
    }
  }

  handleFileInput(files) {
    const file = files[0];
    this.file = undefined;
    setTimeout(() => {
      this.file = FileRepository.createFile({ file });
    });
  }

  resetFiles() {
    if (this.file) this.file.dispose();
    this.file = undefined;
    this.fileInput.nativeElement.value = "";
    this.imageInput.nativeElement.value = "";
  }
}

<div class="MessageComposer">
  <app-attachment
    *ngIf="file"
    [file]="file.model"
    (onDelete)="resetFiles()"
  ></app-attachment>

  <form [formGroup]="chatForm" (submit)="onSubmit()">
    <div class="Uploaders">
      <button type="button" (click)="imageInput.click()">
        <icon-image-upload></icon-image-upload>
        <input
          #imageInput
          style="display: none;"
          type="file"
          accept="image/*"
          (change)="handleFileInput($event.target.files)"
        />
      </button>
      <button type="button" (click)="fileInput.click()">
        <icon-file-upload></icon-file-upload>
        <input
          #fileInput
          style="display: none;"
          type="file"
          accept="*/*"
          (change)="handleFileInput($event.target.files)"
        />
      </button>
    </div>
    <input
      #chatBox
      type="text"
      formControlName="message"
      placeholder="Type something..."
      autocomplete="off"
      autoCorrect="off"
    />
    <button type="submit">
      <icon-send></icon-send>
    </button>
  </form>
</div>
