// create-react-app-simple-chat/src/components/ChannelBrowser/index.js
import React, { useState, useRef } from "react";
import "./index.css";

import { ChannelList } from "../ChannelList";

export function ChannelBrowser({
  userId,
  activeChannelId,
  onChange = () => {},
}) {
  const [searchQuery, setSearchQuery] = useState();

  const timer = useRef();

  const handleSearchQuery = (e) => {
    clearTimeout(timer.current);

    timer.current = setTimeout(() => {
      setSearchQuery(e.target.value);
    }, 200);
  };

  return (
    <div className="ChannelBrowser">
      <div className="Header">
        <h2>Chats</h2>
        <input
          type="search"
          name="search"
          placeholder="Search a channel..."
          onChange={handleSearchQuery}
        />
      </div>

      <ChannelList
        activeChannelId={activeChannelId}
        searchQuery={searchQuery}
        onClick={onChange}
      />
    </div>
  );
}

// messaging-app-with-angular/src/app/chat/ChannelBrowser/channel-browser.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";

@Component({
  selector: "app-channel-browser",
  templateUrl: "./channel-browser.component.html",
  styleUrls: ["./channel-browser.component.css"]
})
export class ChannelBrowser {
  @Output() clickEvent = new EventEmitter<string>();
  @Input() activeChannelId;
  timer;
  searchQuery;

  handleSearchQuery(e) {
    clearTimeout(this.timer);
    this.timer = setTimeout(() => {
      this.searchQuery = e.target.value;
    }, 200);
  }

  joinChannel(value) {
    this.clickEvent.emit(value);
  }
}

<div class="ChannelBrowser">
  <div class="Header">
    <h2>Chats</h2>
    <input
      type="search"
      name="search"
      placeholder="Search a channel..."
      (input)="handleSearchQuery($event)"
    />
  </div>

  <app-channel-list
    [activeChannelId]="activeChannelId"
    [searchQuery]="searchQuery"
    (clickEvent)="joinChannel($event)"
  ></app-channel-list>
</div>
