// create-react-app-single-channel-chat/src/SyncState.js
import { SyncState } from "@amityco/js-sdk";

import { SyncingIcon, SyncedIcon } from "./Icons";

export default function Sync({ value }) {
  const MESSAGES = {
    [SyncState.Default]: "Idle",
    [SyncState.Syncing]: <SyncingIcon />,
    [SyncState.Synced]: <SyncedIcon />,
    [SyncState.Error]: "Error."
  };

  return <em className="syncstate">{MESSAGES[value]}</em>;
}

// messaging-app-with-angular/src/app/chat/MessageItem/SyncState/sync-state.component.ts
import { SyncState as Values } from "@amityco/js-sdk";
import { Component, Input } from "@angular/core";

@Component({
  selector: "app-sync-state",
  templateUrl: "./sync-state.component.html"
})
export class SyncState {
  @Input() value;
  syncValues = Values;
}

<em class="SyncState" *ngIf="value === syncValues.Default">
  Idle
</em>
<em class="SyncState" *ngIf="value === syncValues.Syncing">
  <icon-syncing></icon-syncing>
</em>
<em class="SyncState" *ngIf="value === syncValues.Synced">
  <icon-synced></icon-synced>
</em>
<em class="SyncState" *ngIf="value === syncValues.Error">
  Error.
</em>
