// create-react-app-simple-chat/src/components/MessageList/index.js
import React, { useRef, useState, useEffect } from "react";
import "./index.css";

import { MessageRepository } from "@amityco/js-sdk";

import { MessageItem } from "../MessageItem";

export function MessageList({ channelId }) {
  const [messages, setMessages] = useState([]);

  const collection = useRef();

  useEffect(() => {
    collection.current = MessageRepository.queryMessages({
      channelId,
    });

    collection.current.on("dataUpdated", setMessages);
    collection.current.models && setMessages(collection.current.models);

    return () => collection.current.dispose();
  }, [channelId]);

  const onScroll = (e) => {
    if (!collection.current.hasMore) return;

    const el = e.target;

    const top = el.scrollHeight - el.clientHeight;
    const scroll = -el.scrollTop; // reversed because of the flex direction

    if (top - scroll <= 1) {
      collection.current.nextPage();
    }
  };

  return (
    <div className="MessageList" onScroll={onScroll}>
      {messages.map((message) => (
        <MessageItem key={message.messageId} {...message} />
      ))}
    </div>
  );
}

// vue2-simple-chat/src/components/messages/MessageList.vue
<template>
  <div class="message-list">
    <div ref="messages" class="message-area" @scroll="onscroll">
      <message-item
        :key="message.messageId"
        v-for="message in messages"
        v-bind="message"
      />
      <div v-if="loading" class="svg">
        <Loader />
      </div>
    </div>
  </div>
</template>

<script>
import { MessageRepository } from "@amityco/js-sdk";

import Loader from "@/components/icons/Loader";
import MessageItem from "./MessageItem";

export default {
  components: { Loader, MessageItem },

  props: ["channelId"],

  data: () => ({
    messages: [],
    loading: false,
  }),

  watch: {
    channelId: {
      handler(val) {
        this.liveCollection?.dispose()

        this.loading = true;
        this.messages = [];

        this.liveCollection = MessageRepository.queryMessages({
          channelId: val,
          isDeleted: false,
        });

        this.liveCollection.on("dataUpdated", (messages) => {
          this.messages = messages;
          this.loading = false;
        });

        this.liveCollection.on("dataError", (error) => {
          console.log("The message live collection encountered an error", error);
        });

      },
      immediate: true,
    },
  },

  beforeDestroy() {
    this.liveCollection?.dispose();
  },

  methods: {
    onscroll(e) {
      if (!this.liveCollection.hasMore) return;

      const el = this.$refs.messages;

      const top = el.scrollHeight - el.clientHeight;
      const scroll = -el.scrollTop; // reversed because of the flex direction

      if (top - scroll <= 1) {
        this.loading = true;
        this.liveCollection.nextPage();
      }
    },
  },
};
</script>

<style>
.message-list {
  position: relative;
}

.message-area {
  display: flex;
  flex-direction: column-reverse;
  width: 100%;
  height: 100%;
  padding-top: 1rem;
  overflow: auto;
}

.message-area .svg {
  display: block;
  margin: 0 auto 1rem;
}

</style>
