// create-react-app-simple-chat/src/components/MessageItem/index.js
import React from "react";
import "./index.css";

import { MessageType } from "@amityco/js-sdk";
import { short } from "tiny-human-time";

import { currentUserId } from "../../ascClient";

import { Image } from "../Image";

import { Deleted } from "./Deleted";
import { NotSupported } from "./NotSupported";

import { TextContent } from "./TextContent";
import { ImageContent } from "./ImageContent";
import { FileContent } from "./FileContent";

import { ReactionBar } from "../ReactionBar";
import { ReactionPicker } from "../ReactionPicker";
import { SyncState } from "./SyncState";

const MAPPING = {
  [MessageType.Text]: TextContent,
  [MessageType.Image]: ImageContent,
  [MessageType.File]: FileContent,
};

export function MessageItem({
  messageId,
  userId,
  type,
  data,
  fileId,
  isDeleted,
  createdAt,
  syncState,
  myReactions,
  reactionsCount,
  reactions,
  user: liveUser,
}) {
  const MessageContent = isDeleted ? Deleted : MAPPING[type] ?? NotSupported;

  const user = liveUser.model;

  return (
    <div
      className={`MessageItem ${type} ${
        userId === currentUserId ? "self" : ""
      }`}
    >
      <div className="Avatar">
        {user?.avatarFileId && <Image fileId={user.avatarFileId} />}
      </div>

      <div className="DisplayName">
        {user?.displayName ?? user?.userId ?? userId}
      </div>

      <div className="Content">
        <MessageContent data={data} fileId={fileId} />
      </div>

      <div className="Metadata">
        <ReactionPicker messageId={messageId} myReactions={myReactions} />
        {" • "}
        <em>{short(Date.now(), createdAt)}</em>
        <SyncState value={syncState} />

        {!!reactionsCount && (
          <ReactionBar reactionsCount={reactionsCount} reactions={reactions} />
        )}
      </div>
    </div>
  );
}

// vue2-simple-chat/src/components/messages/MessageItem.vue
<template>
  <div class="message-item" :class="{ self }">
    <div class="avatar">
      <image-component v-if="avatarFileId" :fileId="avatarFileId" />
    </div>

    <div class="displayname">{{ userName }}</div>

    <div class="content">
      <message-content :data="data" :type="type" :fileId="fileId" />
    </div>

    <div class="metadata">
      <reaction-picker :messageId="messageId" :myReactions="myReactions" /> • <em>{{ shortCreated }}</em>
      <sync-state :value="syncState" />
      <reactions-bar
        v-if="!!reactionsCount"
        :reactionsCount="reactionsCount"
        :reactions="reactions"
      />
    </div>
  </div>
</template>

<script>
import { short } from "tiny-human-time";

import { currentUserId } from '../../ascClient';

import ImageComponent from "@/components/Image";
import MessageContent from "./MessageContent";
import ReactionPicker from "@/components/reactions/ReactionPicker";
import SyncState from "./SyncState";
import ReactionsBar from "@/components/reactions/ReactionsBar";

export default {
  inheritAttrs: false,

  components: {
    ImageComponent,
    MessageContent,
    ReactionPicker,
    SyncState,
    ReactionsBar,
  },

  props: [
    "messageId",
    "userId",
    "type",
    "data",
    "fileId",
    "isDeleted",
    "createdAt",
    "syncState",
    "myReactions",
    "reactionsCount",
    "reactions",
    "user",
  ],

  computed: {
    self: ({ userId }) => userId === currentUserId,
    userName: ({ user }) => user?.model?.displayname ?? user?.model?.userId,
    avatarFileId: ({ user }) => user?.model?.avatarFileId,
    shortCreated: ({ createdAt }) => short(Date.now(), createdAt),
  }
};
</script>

<style>
.message-item {
  display: grid;
  grid-template-columns: 2rem max-content;
  grid-template-rows: 1rem 1rem 1fr min-content;
  grid-template-areas:
    "avatar displayname"
    "avatar message"
    ". message"
    ". metadata";

  grid-gap: 0 0.5rem;
  padding: 0 1rem 0.5rem;
}

.message-item .avatar {
  grid-area: avatar;
  width: 2rem;
  height: 2rem;
  background: #ebecef;
  border-radius: 2rem;
}

.message-item .displayname {
  grid-area: displayname;
  color: #636878;
}

.message-item .content {
  grid-area: message; 
  justify-self: end;
}

.message-item .metadata {
  grid-area: metadata;
  position: relative;
  display: flex;
  align-items: center;
  gap: 0.25rem;
  color: #636878;
  font-size: 0.7rem;
}

.message-item .metadata .reaction-bar {
  position: absolute;
  right: 0.5rem;
  top: -1rem;
}

/*****************/

.message-item.self {
  grid-template-columns: max-content;
  grid-template-rows: min-content 1fr min-content;
  grid-template-areas:
    "displayname"
    "message"
    "metadata";
  justify-content: end;
}

.message-item.self .avatar,
.message-item.self .displayname {
  display: none;
}

.message-item.self .content {
  border-radius: 0.5rem 0 0.5rem 0.5rem;
}

</style>
