// messaging-app-with-angular/src/app/login/login.component.ts
import { Component, EventEmitter, Output, ViewChild } from "@angular/core";
import { FormBuilder, Validators } from "@angular/forms";

@Component({
  selector: "app-login",
  templateUrl: "./login.component.html",
  styleUrls: ["./login.component.css"]
})
export class LoginComponent {
  @Output() formSubmittedEvent = new EventEmitter<Object>();
  @ViewChild("persistent") persistentCheckbox;
  loginForm;

  constructor(private formBuilder: FormBuilder) {
    this.loginForm = formBuilder.group({
      name: ["", [Validators.required]],
      password: ["", [Validators.required]]
    });
  }

  onSubmit() {
    if (this.loginForm.status === "VALID") {
      this.formSubmittedEvent.emit({
        userId: this.loginForm.get("name").value,
        persistent: this.persistentCheckbox.nativeElement.checked
      });
    }
  }
}

<div class="Login">
  <div class="Modal">
    <icon-amity></icon-amity>

    <h1>Connect with your favorite people</h1>

    <form [formGroup]="loginForm" (submit)="onSubmit()">
      <input
        type="text"
        name="username"
        placeholder="Username"
        autocomplete="username"
        formControlName="name"
        required
      />

      <input
        type="password"
        name="password"
        placeholder="Password"
        autocomplete="current-password"
        formControlName="password"
        required
      />

      <button type="submit">Continue</button>

      <label>
        <input #persistent type="checkbox" />
        Keep me signed in
      </label>
    </form>
  </div>
</div>

// create-react-app-simple-chat/src/pages/Login/index.js
import React from "react";
import "./index.css";

import { Amity } from "../../components/Amity";

export function Login({ onConnect = () => {} }) {
  const onSubmit = async (e) => {
    e.preventDefault();

    const formdata = Object.fromEntries(new FormData(e.target));
    onConnect(formdata.username, "persistent" in formdata);
  };

  return (
    <div className="Login">
      <div className="Modal">
        <Amity />

        <h1>Connect with your favorite people</h1>

        <form onSubmit={onSubmit}>
          <input
            type="text"
            name="username"
            placeholder="Username"
            autoComplete="username"
            required
          />

          <input
            type="password"
            name="password"
            placeholder="Password"
            autoComplete="current-password"
            required
          />
          <button>Continue</button>

          <label>
            <input type="checkbox" name="persistent" value="true" />
            {"Keep me signed in"}
          </label>
        </form>
      </div>
    </div>
  );
}
