// create-react-app-simple-chat/src/components/ChannelHeader/index.js
import React, { useState, useEffect } from "react";
import "./index.css";

import { ChannelRepository } from "@amityco/js-sdk";

import { MemberIcon } from "../Icons";

export function ChannelHeader({ channelId }) {
  const [channel, setChannel] = useState();

  useEffect(() => {
    const liveObject = ChannelRepository.getChannel(channelId);

    liveObject.on("dataUpdated", setChannel);
    liveObject.model && setChannel(liveObject.model);

    return () => liveObject.dispose();
  }, [channelId]);

  return (
    <div className="ChannelHeader">
      <h3>{channel?.displayName ?? channel?.channelId}</h3>
      {channel?.memberCount > 0 && (
        <>
          {" • "}
          {channel?.memberCount} <MemberIcon />
        </>
      )}
    </div>
  );
}

// messaging-app-with-angular/src/app/chat/ChannelHeader/channel-header.component.ts
import { Component, Input, NgZone } from "@angular/core";
import { ChannelRepository } from "@amityco/js-sdk";

@Component({
  selector: "app-channel-header",
  templateUrl: "./channel-header.component.html",
  styleUrls: ["./channel-header.component.css"]
})
export class ChannelHeader {
  @Input() channelId;
  channel;
  liveObject;

  constructor(private ngZone: NgZone) {}

  ngOnChanges() {
    this.liveObject?.dispose();
    this.liveObject = ChannelRepository.getChannel(this.channelId);
    this.liveObject.on("dataUpdated", (model) => {
      this.ngZone.run(() => {
        this.channel = model;
      });
    });
  }

  ngOnDestroy() {
    this.liveObject?.dispose();
  }
}

<div class="ChannelHeader" *ngIf="channel">
  <h3>
    {{channel.displayName ? channel.displayName : channel.channelId}}
  </h3>
  <div *ngIf="channel?.memberCount > 0">
    {{" • "}} {{channel?.memberCount}}
    <icon-member></icon-member>
  </div>
</div>
