// messaging-app-with-angular/src/app/chat/Image/image.component.ts
import { Component, Input, NgZone } from "@angular/core";
import { FileRepository } from "@amityco/js-sdk";

@Component({
  selector: "app-image",
  templateUrl: "./image.component.html",
  styleUrls: ["./image.component.css"]
})
export class Image {
  @Input() fileId;
  file;
  liveFile;

  constructor(private ngZone: NgZone) {}

  ngOnInit() {
    this.liveFile = FileRepository.getFile(this.fileId);

    if (this.liveFile.model) {
      this.file = this.liveFile.model;
    } else {
      this.liveFile.once("dataUpdated", () => {
        this.ngZone.run(() => {
          this.file = this.liveFile.model;
        });
      });
    }
  }

  ngOnDestroy() {
    this.liveFile?.dispose();
  }
}

<div class="Image">
  <img *ngIf="file" [src]="file.fileUrl" alt="" />
</div>

// create-react-app-simple-chat/src/components/Image/index.js
import React, { useState, useEffect } from "react";
import "./index.css";

import { FileRepository } from "@amityco/js-sdk";

export function Image({ fileId }) {
  const [file, setFile] = useState();

  useEffect(() => {
    const liveObject = FileRepository.getFile(fileId);

    liveObject.on("dataUpdated", setFile);
    liveObject.model && setFile(liveObject.model);

    return () => liveObject.dispose();
  }, [fileId]);

  return (
    <div className="Image">{file && <img src={file.fileUrl} alt="" />}</div>
  );
}
