// create-react-app-simple-chat/src/components/MessageItem/index.js
import React from "react";
import "./index.css";

import { MessageType } from "@amityco/js-sdk";
import { short } from "tiny-human-time";

import { currentUserId } from "../../ascClient";

import { Image } from "../Image";

import { Deleted } from "./Deleted";
import { NotSupported } from "./NotSupported";

import { TextContent } from "./TextContent";
import { ImageContent } from "./ImageContent";
import { FileContent } from "./FileContent";

import { ReactionBar } from "../ReactionBar";
import { ReactionPicker } from "../ReactionPicker";
import { SyncState } from "./SyncState";

const MAPPING = {
  [MessageType.Text]: TextContent,
  [MessageType.Image]: ImageContent,
  [MessageType.File]: FileContent,
};

export function MessageItem({
  messageId,
  userId,
  type,
  data,
  fileId,
  isDeleted,
  createdAt,
  syncState,
  myReactions,
  reactionsCount,
  reactions,
  user: liveUser,
}) {
  const MessageContent = isDeleted ? Deleted : MAPPING[type] ?? NotSupported;

  const user = liveUser.model;

  return (
    <div
      className={`MessageItem ${type} ${
        userId === currentUserId ? "self" : ""
      }`}
    >
      <div className="Avatar">
        {user?.avatarFileId && <Image fileId={user.avatarFileId} />}
      </div>

      <div className="DisplayName">
        {user?.displayName ?? user?.userId ?? userId}
      </div>

      <div className="Content">
        <MessageContent data={data} fileId={fileId} />
      </div>

      <div className="Metadata">
        <ReactionPicker messageId={messageId} myReactions={myReactions} />
        {" • "}
        <em>{short(Date.now(), createdAt)}</em>
        <SyncState value={syncState} />

        {!!reactionsCount && (
          <ReactionBar reactionsCount={reactionsCount} reactions={reactions} />
        )}
      </div>
    </div>
  );
}

// messaging-app-with-angular/src/app/chat/MessageItem/message-item.component.ts
import {
  Component,
  Input,
  ViewChild,
  ViewContainerRef,
  ComponentFactoryResolver
} from "@angular/core";
import { MessageType } from "@amityco/js-sdk";

import { TextContent } from "./Content/text-content.component";
import { ImageContent } from "./Content/image-content.component";
import { FileContent } from "./Content/file-content.component";
import { currentUserId } from "../../client";

import { short } from "tiny-human-time";

const MAPPING = {
  [MessageType.Text]: TextContent,
  [MessageType.Image]: ImageContent,
  [MessageType.File]: FileContent
};

@Component({
  selector: "app-message-item",
  templateUrl: "./message-item.component.html",
  styleUrls: ["./message-item.component.css"]
})
export class MessageItem {
  @ViewChild("content", { read: ViewContainerRef }) content: ViewContainerRef;
  @Input() msg;
  currentUserId = currentUserId;
  timeString = "0s";

  constructor(private resolver: ComponentFactoryResolver) {}

  ngOnChanges() {
    this.timeString = short(Date.now(), this.msg.createdAt);
  }

  ngAfterViewInit() {
    Promise.resolve(null).then(() => this.renderContent());
  }

  renderContent() {
    this.content.clear();
    const classType: any = MAPPING[this.msg.type];
    const factory = this.resolver.resolveComponentFactory(classType);
    const component: any = this.content.createComponent(factory).instance;
    component.data = this.msg.data;
    component.fileId = this.msg.fileId;
  }
}

<div
  class="{{ type }} MessageItem"
  [ngClass]="{'self': msg.userId === currentUserId}"
>
  <div class="Avatar">
    <app-image
      *ngIf="msg.user.avatarFileId"
      [fileId]="msg.user.avatarFileId"
    ></app-image>
  </div>

  <div class="DisplayName">
    {{msg.userId}}
    <!-- {{msg.user.displayName ?? msg.user.userId ?? msg.userId}} -->
  </div>

  <div class="Content">
    <template #content> </template>
  </div>

  <div class="Metadata">
    <app-reaction-picker
      [messageId]="msg.messageId"
      [myReactions]="msg.myReactions"
    ></app-reaction-picker>
    {{" • "}}
    <em>{{timeString}}</em>
    <app-sync-state [value]="msg.syncState"></app-sync-state>
    <app-reaction-bar
      *ngIf="!!msg.reactionsCount"
      [reactionsCount]="msg.reactionsCount"
      [reactions]="msg.reactions"
    ></app-reaction-bar>
  </div>
</div>
