// create-react-app-simple-chat/src/components/ReactionPicker/index.js
import React, { useState, useEffect, useRef } from "react";
import "./index.css";

import { MessageRepository } from "@amityco/js-sdk";

import { REACTION_ICONS } from "./constants";

export function ReactionPicker({ messageId, myReactions = [] }) {
  const [open, setOpen] = useState(false);

  const ref = useRef();

  useEffect(() => {
    const listener = (e) => {
      if (!ref.current.contains(e.target)) setOpen(false);
    };

    document.addEventListener("click", listener);

    return () => {
      document.removeEventListener("click", listener);
    };
  }, []);

  const toggleBar = (e) => {
    e.preventDefault();
    e.stopPropagation();

    setOpen(true);
  };

  const toggleReaction = (reactionName) => async (e) => {
    if (!open) return;

    e.preventDefault();
    e.stopPropagation();

    const action = myReactions.includes(reactionName)
      ? "removeReaction"
      : "addReaction";

    await MessageRepository[action]({
      messageId,
      reactionName,
    });

    setOpen(false);
  };

  return (
    <span ref={ref} className="ReactionPicker">
      <span onClick={toggleBar}>React</span>
      {open && (
        <div className="ReactionButtons">
          {Object.entries(REACTION_ICONS).map(([reaction, Icon]) => (
            <button
              key={reaction}
              rel={reaction}
              className={`ReactionButton ${
                myReactions.includes(reaction) ? "active" : ""
              }`}
              onClick={toggleReaction(reaction)}
            >
              <Icon />
            </button>
          ))}
        </div>
      )}
    </span>
  );
}

// messaging-app-with-angular/src/app/chat/ReactionPicker/reaction-picker.component.ts
import { HostListener, Component, Input } from "@angular/core";
import { MessageRepository } from "@amityco/js-sdk";

import * as Reactions from "../../constants/reactions";

@Component({
  selector: "app-reaction-picker",
  templateUrl: "./reaction-picker.component.html",
  styleUrls: ["./reaction-picker.component.css"]
})
export class ReactionPicker {
  @Input() messageId;
  @Input() myReactions = [];
  open = false;
  wasInside = false;
  REACTION_ICONS = Reactions.REACTION_ICONS;

  @HostListener("click")
  clickInside() {
    this.wasInside = true;
  }

  @HostListener("document:click")
  clickOutside() {
    if (!this.wasInside) this.open = false;
    this.wasInside = false;
  }

  toggleBar() {
    this.open = !this.open;
  }

  toggleReaction(reactionName) {
    const action = this.myReactions.includes(reactionName)
      ? "removeReaction"
      : "addReaction";
    MessageRepository[action]({
      messageId: this.messageId,
      reactionName
    });
    this.open = false;
  }
}

<span class="ReactionPicker">
  <span (click)="toggleBar()">React</span>
  <div class="ReactionButtons" *ngIf="open">
    <button
      *ngFor="let reaction of REACTION_ICONS | keyvalue"
      class="ReactionButton"
      [ngClass]="{'active': myReactions.includes(reaction.key)}"
      (click)="toggleReaction(reaction.key)"
    >
      <app-reaction-icon [iconClass]="reaction.value"></app-reaction-icon>
    </button>
  </div>
</span>
