// messaging-app-with-angular/src/app/chat/MessageList/message-list.component.ts
import { Component, Input, NgZone, HostListener } from "@angular/core";
import { MessageRepository } from "@amityco/js-sdk";

@Component({
  selector: "app-message-list",
  templateUrl: "./message-list.component.html",
  styleUrls: ["./message-list.component.css"]
})
export class MessageList {
  @Input() channelId;
  collection;
  messages;

  constructor(private ngZone: NgZone) {}

  ngOnChanges() {
    this.collection?.dispose();
    this.collection = MessageRepository.queryMessages({
      channelId: this.channelId
    });

    this.collection.on("dataUpdated", () => {
      this.ngZone.run(() => {
        this.messages = this.collection.models;
      });
    });
  }

  ngOnDestroy() {
    this.collection?.dispose();
  }

  @HostListener("scroll", ["$event"])
  onScroll(e) {
    if (!this.collection.hasMore) return;

    const el = e.target;
    const top = el.scrollHeight - el.clientHeight;
    const scroll = -el.scrollTop;

    if (top - scroll <= 1) {
      this.collection.nextPage();
    }
  }

  messageId(index, obj) {
    return obj.messageId;
  }
}

<app-message-item
  *ngFor="let msg of messages ; trackBy: messageId"
  [msg]="msg"
></app-message-item>

// create-react-app-simple-chat/src/components/MessageList/index.js
import React, { useRef, useState, useEffect } from "react";
import "./index.css";

import { MessageRepository } from "@amityco/js-sdk";

import { MessageItem } from "../MessageItem";

export function MessageList({ channelId }) {
  const [messages, setMessages] = useState([]);

  const collection = useRef();

  useEffect(() => {
    collection.current = MessageRepository.queryMessages({
      channelId,
    });

    collection.current.on("dataUpdated", setMessages);
    collection.current.models && setMessages(collection.current.models);

    return () => collection.current.dispose();
  }, [channelId]);

  const onScroll = (e) => {
    if (!collection.current.hasMore) return;

    const el = e.target;

    const top = el.scrollHeight - el.clientHeight;
    const scroll = -el.scrollTop; // reversed because of the flex direction

    if (top - scroll <= 1) {
      collection.current.nextPage();
    }
  };

  return (
    <div className="MessageList" onScroll={onScroll}>
      {messages.map((message) => (
        <MessageItem key={message.messageId} {...message} />
      ))}
    </div>
  );
}
