// create-react-app-simple-chat/src/components/Image/index.js
import React, { useState, useEffect } from "react";
import "./index.css";

import { FileRepository } from "@amityco/js-sdk";

export function Image({ fileId }) {
  const [file, setFile] = useState();

  useEffect(() => {
    const liveObject = FileRepository.getFile(fileId);

    liveObject.on("dataUpdated", setFile);
    liveObject.model && setFile(liveObject.model);

    return () => liveObject.dispose();
  }, [fileId]);

  return (
    <div className="Image">{file && <img src={file.fileUrl} alt="" />}</div>
  );
}

// vue2-simple-chat/src/components/Image.vue
<template>
  <div class="image">
    <img :src="fileUrl" :title="alt" :alt="alt" loading="lazy" />
  </div>
</template>

<script>
import { FileRepository } from "@amityco/js-sdk";

export default {
  props: ["fileId", "alt"],

  computed: {
    fileUrl: ({ file }) => {
      if (!file.fileUrl) return null;

      return file.fileUrl.startsWith("blob:")
        ? file.fileUrl
        : `${file.fileUrl}?size=medium`;
    },
  },

  data: () => ({
    file: {},
  }),

  watch: {
    fileId: {
      handler(val) {
        if (this.liveObject) this.liveObject.dispose();
        if (!val) return;

        this.liveObject = FileRepository.getFile(val);

        this.liveObject.on("dataUpdated", (model) => (this.file = model));
        this.file = this.liveObject.model ?? {};
      },
      immediate: true,
    },
  },

  beforeDestroy() {
    this.liveObject?.dispose();
  },
};
</script>

<style scoped>
.image {
  width: 100%;
  height: 100%;
}

.image img {
  display: block;
  width: 100%;
  height: 100%;
  object-fit: contain;
  object-position: center;
  opacity: 0;
}

.image img[src] {
  opacity: 1;
}
</style>
