// messaging-app-with-angular/src/app/chat/ChannelItem/channel-item.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";
import * as humanize from "tiny-human-time";

@Component({
  selector: "app-channel-item",
  templateUrl: "./channel-item.component.html",
  styleUrls: ["./channel-item.component.css"]
})
export class ChannelItem {
  @Output() clickEvent = new EventEmitter<string>();
  @Input() channel;
  @Input() active;
  timeString = "";

  ngOnChanges() {
    this.timeString = humanize(Date.now(), this.channel.lastActivity);
  }

  joinChannel() {
    this.clickEvent.emit(this.channel.channelId);
  }
}

<div
  class="ChannelItem"
  [ngClass]="{' active': active}"
  (click)="joinChannel()"
>
  <div class="Avatar">
    <app-image
      *ngIf="channel.avatarFileId"
      [fileId]="channel.avatarFileId"
    ></app-image>
  </div>
  <div class="DisplayName">
    {{channel.displayName ? channel.displayName : channel.channelId}}
  </div>
  <div class="Metadata">
    {{timeString}} • {{channel.memberCount}} <icon-member></icon-member>
  </div>
  <div *ngIf="!!channel.unreadCount" class="UnreadCount">
    {{channel.unreadCount}}
  </div>
</div>

// create-react-app-simple-chat/src/components/ChannelItem/index.js
import React from "react";
import "./index.css";

import humanize from "tiny-human-time";
import { Image } from "../Image";

export function ChannelItem({
  channelId,
  displayName,
  avatarFileId,
  lastActivity,
  unreadCount,
  active,
  onClick = () => {},
}) {
  return (
    <div
      className={`ChannelItem ${active ? "active" : ""}`}
      onClick={() => onClick(channelId)}
    >
      <div className="Avatar">
        {avatarFileId && <Image fileId={avatarFileId} />}
      </div>
      <div className="DisplayName">{displayName ?? channelId}</div>
      <div className="LastActivity">{humanize(Date.now(), lastActivity)}</div>
      {!!unreadCount && <div className="UnreadCount">{unreadCount}</div>}
    </div>
  );
}
