// messaging-app-with-angular/src/app/chat/ReactionBar/reaction-bar.component.ts
import { Component, Input } from "@angular/core";
import * as Reactions from "../../constants/reactions";

@Component({
  selector: "app-reaction-bar",
  templateUrl: "./reaction-bar.component.html",
  styleUrls: ["./reaction-bar.component.css"]
})
export class ReactionBar {
  @Input() reactionsCount;
  @Input() reactions = {};
  REACTION_ICONS = Reactions.REACTION_ICONS;
}

<div class="ReactionBar">
  <span
    *ngFor="let reaction of REACTION_ICONS | keyvalue | removereactions:reactions; let i = index"
    class="ReactionMedal"
    [style.zIndex]="REACTION_ICONS.length - i"
  >
    <app-reaction-icon [iconClass]="reaction.value"></app-reaction-icon>
  </span>
  <span *ngIf="reactionsCount > 1" class="ReactionCount">
    {{reactionsCount}}
  </span>
</div>

// create-react-app-simple-chat/src/components/ReactionBar/index.js
import React from "react";
import "./index.css";

import { REACTION_ICONS } from "../ReactionPicker/constants";

export function ReactionBar({ reactionsCount, reactions }) {
  return (
    <div className="ReactionBar">
      {Object.entries(REACTION_ICONS)
        .filter(([reaction]) => reactions[reaction] > 0)
        .map(([reaction, Icon], i, a) => (
          <span
            key={reaction}
            className="ReactionMedal"
            style={{ zIndex: a.length - i }}
          >
            <Icon />
          </span>
        ))}
      {reactionsCount > 1 && (
        <span className="ReactionCount">{reactionsCount}</span>
      )}
    </div>
  );
}
