// create-react-app-simple-chat/src/components/MessageItem/ImageContent.js
import { useEffect, useState } from "react";

import { FileRepository } from "@amityco/js-sdk";

export function ImageContent({ data: { caption } = {}, fileId }) {
  const [fileUrl, setFileUrl] = useState();

  useEffect(() => {
    const file = FileRepository.getFile(fileId);

    if (file.model) {
      setFileUrl(file.model.fileUrl);
    } else {
      file.once("dataUpdated", (model) => {
        setFileUrl(model.fileUrl);
      });
    }
  }, [fileId]);

  if (!fileUrl) return null;

  const sizedUrl = fileUrl.startsWith("blob:")
    ? fileUrl
    : `${fileUrl}?size=medium`;

  return (
    <>
      <div className="Image">
        <img src={sizedUrl} alt={caption} />
      </div>
      {caption && (
        <div className="Text">
          <em>{caption}</em>
        </div>
      )}
    </>
  );
}

// messaging-app-with-angular/src/app/chat/MessageItem/Content/image-content.component.ts
import { Component, Input, NgZone } from "@angular/core";

import { FileRepository } from "@amityco/js-sdk";

@Component({
  selector: "app-image-content",
  templateUrl: "./image-content.component.html"
})
export class ImageContent {
  @Input() data;
  @Input() fileId;
  sizedUrl;
  liveFile;

  constructor(private ngZone: NgZone) {}

  ngOnInit() {
    this.liveFile = FileRepository.getFile(this.fileId);

    if (this.liveFile.model) {
      this.setFile(this.liveFile.model.fileUrl);
    } else {
      this.liveFile.once("dataUpdated", (model) => {
        this.setFile(model.fileUrl);
      });
    }
  }

  ngOnDestroy() {
    this.liveFile.dispose();
  }

  setFile(url) {
    this.ngZone.run(() => {
      this.sizedUrl = url.startsWith("blob:") ? url : `${url}?size=medium`;
    });
  }
}

<div *ngIf="sizedUrl">
  <div class="Image">
    <img [src]="sizedUrl" [alt]="data.caption" />
  </div>
  <div *ngIf="data.caption" class="Text">
    <em>{{data.caption}}</em>
  </div>
</div>
